#!/usr/bin/env ruby
#https://gist.github.com/wacko/62560b45c1d191859d6b
# Validates that you don't commit forbidden keywords to the repo
# You can skip this checking with 'git commit --no-verify'

`if [ -e ./.git/hooks/pre-commit ]; then
    echo "Running local pre commit"
    ./.git/hooks/pre-commit "$@"
fi`

puts "Pre-commit running"
exit 0 if ARGV.include?('--no-verify')
# Update this list with your own forbidden keywords
KEYWORDS = %w(dd\( console\.log debugger dontcommit '>>>>>>>')

def red(text)    "\033[31m#{text}\033[0m"; end
def yellow(text) "\033[33m#{text}\033[0m"; end

# list all the files staged for commit
files_changed = %x(git diff --cached --name-only --).split

# search files for keywords
%x(git grep -q -E "#{KEYWORDS.join('|')}" #{files_changed.join(' ')})
grep_result_exists = $?.exitstatus.zero?
#%x(git diff HEAD -G "#{KEYWORDS.join('|')} #{files_changed.join(' ')}")
#grep_diff_exists = $?.exitstatus.zero?
#if grep_result_exists || grep_diff_exists
if grep_result_exists && files_changed.count > 0
  puts "# Check following lines:"
  files_changed.each do |file|
    KEYWORDS.each do |keyword|
      # TODO dont grep file, grep diff, what if remove code but dont add to index and commit again
      # log TODO count in commit
      #https://github.com/SirEelBiscuits/globs/blob/7b95f838a60b86f386bcfb0f23beec1f84b018d3/devinstall/pre-commit
      %x(git grep -q #{keyword} #{file})
      if $?.exitstatus.zero?
        line = %x(git grep -n #{keyword} #{file} | awk -F ":" '{print $2}').split.join(', ')
        puts "#\t#{red(file)}:#{line} contains #{yellow keyword}."
      end
    end
  end
  puts "Use 'git commit --no-verify' to skip this validation"
  exit 1
end
